// Auto-generated by cdm install -- do not edit
import type { HexString, SizedHex } from "polkadot-api";

declare module "@parity/product-sdk-contracts" {
    interface Contracts {
        "@w3s/playground-registry": {
            methods: {
                getAppCount: { args: []; response: number };
                getDomainAt: { args: [index: number]; response: string };
                getMetadataUri: { args: [domain: string]; response: string };
                getOwner: { args: [domain: string]; response: HexString };
                getVisibility: { args: [domain: string]; response: number };
                getOwnerAppCount: { args: [owner: HexString]; response: number };
                getOwnerDomainAt: { args: [owner: HexString, index: number]; response: string };
                getSudo: { args: []; response: HexString };
                isAdmin: { args: [addr: HexString]; response: boolean };
                isBlacklisted: { args: [account: HexString]; response: boolean };
                getPoints: { args: [account: HexString]; response: bigint };
                getApps: { args: [start: number, count: number]; response: { total: number; scanned: number; entries: { index: number; domain: string; metadata_uri: string; owner: HexString; visibility: number; publisher: HexString }[] } };
                getStarCount: { args: [domain: string]; response: number };
                getModCount: { args: [domain: string]; response: number };
                getLineageCount: { args: []; response: number };
                getLineage: { args: [start: number, count: number]; response: { child: string; source: string }[] };
                hasStarred: { args: [voter: HexString, domain: string]; response: boolean };
                getAppData: { args: [domains: string[], voter: HexString]; response: { domain: string; metadata_uri: string; owner: HexString; visibility: number; publisher: HexString; star_count: number; mod_count: number; has_starred: boolean }[] };
                getPointBreakdown: { args: [account: HexString]; response: { mod_points: bigint; star_points: bigint; total: bigint } };
                isPinned: { args: [domain: string]; response: boolean };
                getPinnedApps: { args: []; response: { index: number; domain: string; metadata_uri: string; owner: HexString; visibility: number; publisher: HexString }[] };
                getBuilderCount: { args: []; response: number };
                getBuilders: { args: [start: number, count: number]; response: { total: number; scanned: number; entries: { account: HexString; score: bigint }[] } };
                pin: { args: [domain: string]; response: undefined };
                unpin: { args: [domain: string]; response: undefined };
                star: { args: [domain: string]; response: undefined };
                publish: { args: [domain: string, metadata_uri: string, visibility: number, modded_from: string]; response: undefined };
                setVisibility: { args: [domain: string, visibility: number]; response: undefined };
                unpublish: { args: [domain: string]; response: undefined };
                addAdmin: { args: [admin: HexString]; response: undefined };
                removeAdmin: { args: [admin: HexString]; response: undefined };
                adminSetDeployAwardCount: { args: [account: HexString, count: number]; response: undefined };
                adminSetAppSocialCounts: { args: [domain: string, star_count: number, mod_count: number]; response: undefined };
                setBlacklisted: { args: [accounts: HexString[], value: boolean]; response: undefined };
                setFrozen: { args: [value: boolean]; response: undefined };
                isFrozen: { args: []; response: boolean };
                setVerifier: { args: [verifier: HexString]; response: undefined };
                getVerifier: { args: []; response: HexString };
                importApp: { args: [domain: string, owner: HexString, publisher: HexString, visibility: number, metadata_uri: string]; response: undefined };
                importApps: { args: [apps: { domain: string; owner: HexString; publisher: HexString; visibility: number; metadata_uri: string }[]]; response: undefined };
                importPinned: { args: [domain: string]; response: undefined };
                importLineage: { args: [entries: { child: string; source: string }[]]; response: undefined };
                importPoints: { args: [entries: { account: HexString; total: bigint }[]]; response: undefined };
                importSocialCounts: { args: [entries: { domain: string; star_count: number; mod_count: number }[]]; response: undefined };
            };
        };
        "@w3s/playground-identity": {
            methods: {
                setIdentity: { args: [root_pubkey: SizedHex<32>, signature: number[]]; response: undefined };
                clearIdentity: { args: []; response: undefined };
                isVerified: { args: [account: HexString]; response: boolean };
                rootOf: { args: [account: HexString]; response: SizedHex<32> };
                getRootAccount: { args: [account: HexString]; response: SizedHex<32> };
                getRootAccounts: { args: [accounts: HexString[]]; response: SizedHex<32>[] };
                adminSetIdentity: { args: [account: HexString, root_pubkey: SizedHex<32>]; response: undefined };
                adminClearIdentity: { args: [account: HexString]; response: undefined };
                addAdmin: { args: [admin: HexString]; response: undefined };
                removeAdmin: { args: [admin: HexString]; response: undefined };
                setFrozen: { args: [value: boolean]; response: undefined };
                importIdentities: { args: [accounts: HexString[], roots: SizedHex<32>[]]; response: undefined };
            };
        };
        "@w3s/playground-open-verifier": {
            methods: {
                isVerified: { args: [_account: HexString]; response: boolean };
                rootOf: { args: [account: HexString]; response: SizedHex<32> };
                getRootAccount: { args: [account: HexString]; response: SizedHex<32> };
                getRootAccounts: { args: [accounts: HexString[]]; response: SizedHex<32>[] };
                faucet: { args: []; response: undefined };
                canClaim: { args: [account: HexString]; response: boolean };
                lastClaimAt: { args: [account: HexString]; response: number };
                setFrozen: { args: [value: boolean]; response: undefined };
                getSudo: { args: []; response: HexString };
                isFrozen: { args: []; response: boolean };
            };
        };
    }
}
