// Copyright (C) Parity Technologies (UK) Ltd.
// SPDX-License-Identifier: Apache-2.0

// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import { beforeEach, describe, expect, it, vi } from "vitest";

const { checkDomainAvailabilityMock, findAvailableRandomNameMock } = vi.hoisted(() => ({
    checkDomainAvailabilityMock: vi.fn(),
    findAvailableRandomNameMock: vi.fn(),
}));

vi.mock("../deploy/availability.js", async (importOriginal) => ({
    ...(await importOriginal<typeof import("../deploy/availability.js")>()),
    checkDomainAvailability: checkDomainAvailabilityMock,
}));
vi.mock("./randomName.js", async (importOriginal) => ({
    ...(await importOriginal<typeof import("./randomName.js")>()),
    findAvailableRandomName: findAvailableRandomNameMock,
}));

import { resolveDomain } from "./domain.js";
import { FREE_DOMAIN_SUFFIX_NOTE } from "./randomName.js";

describe("resolveDomain — autoGenerated flag + suffix note", () => {
    beforeEach(() => {
        checkDomainAvailabilityMock.mockReset();
        findAvailableRandomNameMock.mockReset();
    });

    it("flags an explicit --dot as NOT auto-generated and emits no suffix note", async () => {
        checkDomainAvailabilityMock.mockResolvedValue({
            status: "available",
            label: "my-site",
            fullDomain: "my-site.paseo",
            note: null,
        });
        const messages: string[] = [];
        const resolved = await resolveDomain({
            env: "paseo-next-v2",
            providedDot: "my-site",
            source: { kind: "url", url: "https://example.com" },
            signer: null,
            onMessage: (m) => messages.push(m),
        });

        expect(resolved.autoGenerated).toBe(false);
        expect(messages.some((m) => m.includes(FREE_DOMAIN_SUFFIX_NOTE))).toBe(false);
        expect(findAvailableRandomNameMock).not.toHaveBeenCalled();
    });

    it("flags an auto-generated name and explains the suffix inline", async () => {
        findAvailableRandomNameMock.mockResolvedValue({
            label: "example-com-urcn30",
            availability: { status: "available", fullDomain: "example-com-urcn30.paseo" },
        });
        const messages: string[] = [];
        const resolved = await resolveDomain({
            env: "paseo-next-v2",
            providedDot: null,
            source: { kind: "url", url: "https://example.com" },
            signer: null,
            onMessage: (m) => messages.push(m),
        });

        expect(resolved.autoGenerated).toBe(true);
        expect(resolved.fullDomain).toBe("example-com-urcn30.paseo");
        expect(messages.some((m) => m.includes(FREE_DOMAIN_SUFFIX_NOTE))).toBe(true);
    });
});
