// Copyright (C) Parity Technologies (UK) Ltd.
// SPDX-License-Identifier: Apache-2.0

// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/**
 * Resolve the DotNS label to deploy under — either the user's `--dot` (or
 * typed input from the TUI), validated for availability, or an
 * auto-generated name derived from the site source (URL hostname or local
 * directory basename).
 *
 * Pure logic (no React/Ink) so both the headless `dot decentralize --site=...`
 * path and the interactive `validate-domain` stage can share it.
 */

import { withSpan } from "../../telemetry.js";
import { getEnvTld, type Env } from "../../config.js";
import { checkDomainAvailability, formatAvailability } from "../deploy/availability.js";
import { normalizeDomain } from "../deploy/playground.js";
import type { ResolvedSigner } from "../signer.js";
import type { DecentralizeSource } from "./run.js";
import { findAvailableRandomName, FREE_DOMAIN_SUFFIX_NOTE } from "./randomName.js";

export interface ResolveDomainOptions {
    env: Env;
    /** When set, treated as the requested label/full-domain (with or without the env TLD suffix). */
    providedDot: string | undefined | null;
    /** Site source (URL or local directory) — drives the auto-name when `providedDot` is empty. */
    source: DecentralizeSource;
    /** Used for "already owned by you" availability detection. */
    signer: ResolvedSigner | null;
    /** Optional progress sink (TUI surfaces these as a single line). */
    onMessage?: (message: string) => void;
}

export interface ResolvedDomain {
    label: string;
    fullDomain: string;
    /** Advisory note from the availability check (e.g. PoP requirement). */
    note: string | null;
    /**
     * True when the label was auto-generated from the site URL (no `--dot` /
     * blank TUI input). Drives the inline "why the random suffix?" explanation
     * so the generated `-urcn30`-style tail doesn't read as a bug.
     */
    autoGenerated: boolean;
}

export async function resolveDomain(opts: ResolveDomainOptions): Promise<ResolvedDomain> {
    const { env, providedDot, source, signer, onMessage } = opts;

    if (providedDot) {
        const normalized = normalizeDomain(providedDot, getEnvTld(env));
        onMessage?.(`\n▸ Checking ${normalized.fullDomain}…`);
        const availability = await withSpan(
            "cli.decentralize.availability",
            "check domain availability",
            () =>
                checkDomainAvailability(normalized.label, {
                    env,
                    ownerSs58Address: signer?.address,
                }),
        );
        if (availability.status === "reserved" || availability.status === "taken") {
            throw new Error(formatAvailability(availability));
        }
        if (availability.status === "unknown") {
            onMessage?.(`\n⚠ ${formatAvailability(availability)} — continuing anyway.`);
        }
        const note =
            availability.status === "available" && availability.note ? availability.note : null;
        return {
            label: normalized.label,
            fullDomain: normalized.fullDomain,
            note,
            autoGenerated: false,
        };
    }

    const sourceDisplay = source.kind === "url" ? source.url : source.directory;
    onMessage?.(`\n▸ Picking a free .${getEnvTld(env)} name from ${sourceDisplay}…`);
    const chosen = await withSpan(
        "cli.decentralize.random-name",
        "find available random name",
        () =>
            findAvailableRandomName({
                env,
                ownerSs58Address: signer?.address,
                siteUrl: source.kind === "url" ? source.url : undefined,
                localPath: source.kind === "path" ? source.directory : undefined,
            }),
    );
    onMessage?.(`  → ${chosen.availability.fullDomain}`);
    // Explain the suffix inline so the generated tail isn't read as a bug. The
    // headless path RELIES on this emission (its only surface for the note); the
    // TUI sees it only transiently in the validate stage and re-shows it as a
    // persistent Hint in ConfirmStage. Don't "deduplicate" it; that breaks headless.
    onMessage?.(`  ${FREE_DOMAIN_SUFFIX_NOTE}`);
    return {
        label: chosen.label,
        fullDomain: chosen.availability.fullDomain,
        note: null,
        autoGenerated: true,
    };
}
